b221210566(5)/Controllers/ApiConsumeController.cs
using b221210566_5_.Data;
using b221210566_5_.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace b221210566_5_.Controllers
{
    public class ApiConsumeController : Controller
    {
        ApplicationDbContext _context;
        public ApiConsumeController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Appointments> appointments = new List<Appointments>();
            var httpClient = new HttpClient();
            var response = await httpClient.GetAsync("https://localhost:7177/api/ApiConsumeController/");
            var jsondata = await response.Content.ReadAsStringAsync();
            appointments = JsonConvert.DeserializeObject<List<Appointments>>(jsondata);
            return View(appointments);
        }
    }
}

b221210566(5)/Controllers/AppointmentController.cs
using b221210566_5_.Data;
using b221210566_5_.Models;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SQLitePCL;
using System.Linq;
using System.Text;

namespace b221210566_5_.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly ILogger<AppointmentController> _logger;
        private readonly ApplicationDbContext _context;
        private static Employee _selectedEmployee;
        private static Department _selectedDepartment;

        public AppointmentController(ILogger<AppointmentController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.Departments = _context.Departments.ToList();
            return View();
        }
        [HttpPost]
        public IActionResult fetchDepartments()
        {
            var departments = _context.Departments.ToList();
            ViewBag.Departments = departments;
            return View("Index");

        }

        [HttpPost]
        public IActionResult FetchEmployees(string departmentName)
        {
            _selectedDepartment = _context.Departments.AsNoTracking().FirstOrDefault(x => x.Name == departmentName);
            var employees = _context.DepEmployees
                .Where(e => e.Department.Name == departmentName)
                .Include(e => e.Employee)
                 .Select(e => e.Employee)
                .ToList();
            ViewBag.Employees = employees;

            return View("Index");
        }

        [HttpPost]
        public IActionResult FetchAvailableTimes(string employeeName, DateOnly date)
        {
            var availableTimes = GetAvailableTimes(employeeName, date);

            ViewBag.AvailableTimes = availableTimes;
            return View("Index");
        }

        public List<string> GetAvailableTimes(string employeeId, DateOnly date)
        {
            _selectedEmployee = _context.Employees.AsNoTracking().FirstOrDefault(x => x.Id == employeeId);

            var appointments = _context.appointmentEmployees.Where(x=>x.EmployeeId == employeeId)
                .Include(x=>x.Appointment)
                .Select(a => a.Appointment.Time)
                .ToList();

            //Tüm zaman aralıklarını oluştur(09:00'dan 17:00'ye kadar saat başı)
            var allTimes = Enumerable.Range(9, 9) // Saatler: 9, 10, ..., 17
                .Select(hour => TimeOnly.FromTimeSpan(new TimeSpan(hour, 0, 0))) // Saatleri TimeOnly'e dönüştür
                .ToList();


            // Uygun saatleri belirle
            var availableTimes = allTimes
                .Where(t => !appointments.Contains(t)) // Çakışmayan saatler
                .Select(t => t.ToString("HH:mm")) // String'e dönüştür
                .ToList();

            // Saatleri düz bir string olarak döndür (virgülle ayrılmış)
            return availableTimes;
        }
        [HttpPost]
        public IActionResult create(TimeOnly time)
        {
            var employee = _selectedEmployee;
            var dep = _selectedDepartment;
            var AppEmployee = _context.Employees.AsNoTracking().FirstOrDefault(e => e.Id == employee.Id);


            AppointmentEmployee appointmentEmployee = new AppointmentEmployee();
            DepEmployee depEmployee1 = new DepEmployee();


            Appointments appointments = new Appointments()
            {
                Date = DateOnly.FromDateTime(DateTime.Now.AddDays(1).Date),
                Time = time,
            };
            DepEmployee depEmployee = new DepEmployee()
            {
                Department = dep,
            };


            _context.appointments.Add(appointments);
            _context.SaveChanges();
            appointmentEmployee.AppointmentId = appointments.AppNo;
            appointmentEmployee.EmployeeId = employee.Id;
            _context.appointmentEmployees.Add(appointmentEmployee);
            _context.SaveChanges();
            return RedirectToAction("AddSuccesed");
        }
        public IActionResult AddSuccesed()
        {
            ViewBag.Message = " Appointment successfully added.";
            return View();
        }


    }

}

b221210566(5)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - b221210566_5_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/b221210566_5_.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Beauty Corner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Servises">Servies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Team">Team</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Index">Create Appointment</a>
                            </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MyApp">My Appointments</a>
                            </li>
                        }
                        @if (User.IsInRole("Manager"))

                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ApprovedScudule">ApprovalScudule</a>
                            </li>
                        }
                        @if (User.IsInRole("Employee") || User.IsInRole("Manager") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Scudule">Scudule</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Manager" asp-action="Index">Add Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Add Employee</a>
                            </li> 
                         
                        }
                        @if (User.IsInRole("Employee") || User.IsInRole("Admin"))

                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AIController" asp-action="AnalyzePhoto"> AI </a>
                            </li>
                        }
                        @if (User.IsInRole("Manager") || User.IsInRole("Admin"))

                         {
                             <li class="nav-item">
                                 <a class="nav-link text-dark" asp-area="" asp-controller="ApiConsume" asp-action="Index"> Delete </a>
                             </li>
                         }
                       
                        
                    </ul>
                    <partial name="_LoginPartial" /> 
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a herf="#">
                <img src="~/image/71473bec7f03f0cb0ef76cf31675d3a5.jpg" alt="Alternate Text" />
            </a>
            <a herf="#">
                <img src="~/image/8cd23114cef4c71da0c454636450959f.jpg" alt="Alternate Text" />
            </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>